#!/bin/bash
#
# XTF test utilities (arm64).
#

# Arch-specific environment overrides.
function xtf_arch_prepare()
{
    export FW_PREFIX="${FW_PREFIX:-/usr/lib/u-boot/qemu_arm64/}"
    export QEMU_PREFIX="${QEMU_PREFIX:-/usr/local/bin/}"
    export XEN_BINARY="${XEN_BINARY:-${WORKDIR}/xen}"
    export XEN_CMDLINE="${XEN_CMDLINE:-loglvl=all dom0_mem=128M noreboot console_timestamps=boot console=dtuart}"
    export XTF_SRC_BRANCH="${XTF_SRC_BRANCH:-safety-staging}"
    export XTF_SRC_URI="${XTF_SRC_URI:-https://gitlab-ci-token:${CI_JOB_TOKEN}@gitpct.epam.com/rec-fusa/xtf.git}"
    export XTF_SRC_VARIANTS="mmu64le"
}

# Perform arch-specific XTF environment setup.
function xtf_arch_setup()
{
    # Crude check for local testing
    if [ ! -d imagebuilder ]; then
        git clone --depth 1 https://gitlab.com/xen-project/imagebuilder.git
    fi

    local num_domus=${XTF_NUM_DOMUS:-1}

    cat > ${WORKDIR}/config <<EOF
MEMORY_START="0x40000000"
MEMORY_END="0xC0000000"

XEN="xen"
XEN_CMD="${XEN_CMDLINE}"

DEVICE_TREE="virt-gicv3.dtb"

DOM0_KERNEL="xtf-test"

NUM_DOMUS=${num_domus}

LOAD_CMD="tftpb"
UBOOT_SOURCE="boot.source"
UBOOT_SCRIPT="boot.scr"
DBG_FDT_PRINT_CHOSEN=1
EOF
    for i in $(seq 0 $((num_domus - 1))); do
        cat >> ${WORKDIR}/config <<DOMUEOF
DOMU_KERNEL[$i]="Image"
DOMU_RAMDISK[$i]="domU-rootfs.cpio.gz"
DOMU_MEM[$i]=128
DOMUEOF
    done
    cp ${XTF_BINARY} ${WORKDIR}/xtf-test

    # Generate virt-gicv3.dtb
    ${QEMU_PREFIX}qemu-system-aarch64 \
        -cpu cortex-a53 \
        -machine virt,virtualization=true,gic-version=3 \
        -m 2048 \
        -smp 2 \
        -machine dumpdtb=${WORKDIR}/virt-gicv3.dtb

    # Decompile host's DTB into a readable format
    dtc -I dtb -O dts -o ${WORKDIR}/virt-gicv3.dts ${WORKDIR}/virt-gicv3.dtb

    # Generate U-Boot environment
    bash -x imagebuilder/scripts/uboot-script-gen \
        -t tftp \
        -d ${WORKDIR}/ \
        -c ${WORKDIR}/config

    export TEST_CMD="${QEMU_PREFIX}qemu-system-aarch64 \
        -cpu cortex-a53 \
        -machine virt,virtualization=true,gic-version=3 \
        -m 2048 \
        -smp 2 \
        -no-reboot \
        -nodefaults \
        -display none \
        -monitor none \
        -serial stdio \
        -device virtio-net-pci,netdev=n0,id=net0 \
        -netdev user,id=n0,tftp=${WORKDIR} \
        -bios ${FW_PREFIX}u-boot.bin \
    "

    export UBOOT_CMD="virtio scan; dhcp; tftpb 0x40000000 boot.scr; source 0x40000000"
}
