variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

workflow:
  name: '$PIPELINE_NAME_PREFIX | $CI_COMMIT_REF_NAME | $CI_COMMIT_TITLE'
  rules:
    - if: '$RUN_UBSAN == "true"'
      variables:
        PIPELINE_NAME_PREFIX: "UBSAN"
    - if: '$RUN_COVERAGE == "true"'
      variables:
        PIPELINE_NAME_PREFIX: "COVERAGE"
    - if: '$RUN_FUZZER == "true"'
      variables:
        PIPELINE_NAME_PREFIX: "FUZZER"
    - if: '$RUN_MINERVA == "true"'
      variables:
        PIPELINE_NAME_PREFIX: "MINERVA"
    - when: always
      variables:
        PIPELINE_NAME_PREFIX: "RELEASE"

stages:
  - artifacts
  - build
  - test
  - trace
  - analyze

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - unknown_failure

include:
  - local: 'automation/renesas-gitlab-ci/artifacts.yaml'
    rules:
      - if: '$RUN_FUZZER != "true"'
  - local: 'automation/renesas-gitlab-ci/build.yaml'
    rules:
      - if: '$RUN_FUZZER != "true"'
  - local: 'automation/renesas-gitlab-ci/test.yaml'
    rules:
      - if: '$RUN_FUZZER != "true"'
  - local: 'automation/renesas-gitlab-ci/trace.yaml'
    rules:
      - if: '$RUN_FUZZER != "true"'
  - local: 'automation/renesas-gitlab-ci/analyze.yaml'
    rules:
      - if: '$RUN_FUZZER != "true"'
  - local: 'automation/renesas-gitlab-ci/fuzzer.yaml'
    rules:
      - if: '$RUN_FUZZER == "true"'
  - local: 'automation/renesas-gitlab-ci/minerva.yaml'
    rules:
      - if: '$RUN_MINERVA == "true"'
