variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

workflow:
  rules:
    - when: always

stages:
  - artifacts
  - build
  - test
  - trace
  - analyze

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - unknown_failure

include:
  - local: 'automation/renesas-gitlab-ci/artifacts.yaml'
  - local: 'automation/renesas-gitlab-ci/build.yaml'
  - local: 'automation/renesas-gitlab-ci/test.yaml'
  - local: 'automation/renesas-gitlab-ci/trace.yaml'
  - local: 'automation/renesas-gitlab-ci/analyze.yaml'
