env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "L2NPXTePd/8gIWfrgNQccTkBAg5swHaT/vVx9as7WHO8nVbw+D78Hfy4If57SUGcl9f+fhOTx2rw9IhoJPiGfSgqRkE7uJ79vJya/T5moD1EfMDjygQHJWFCEi2iB5FVYy2W/RCVcSzrl5czxCJ2Ck4f3k1vHiRBnFSpuVVMB6d+oq+HGdiY+RfLWfLU/RcHxZUIFfAyb+b6xLZq8/OZQ91g0oh0RV169WnI6svXkEa7wj4Q5dXPdsfPiWmx++5bCACxqOscdbfpPt2hE5j82v4vdKYWoYjFpI6B/hb2EbXGHNc+nhmREOGF1pS7UFvgpZiEGxPkwgVBVfj2aewOAowuqTo/R0h0t5byjuM30r1VINJu5VTG7Hntvfzj3VjYJUPPz+WcQ6nADxxdUGoQ5EzfYCPD1+A5qbUdj787cDK8YoFfEbz0/BXA58Ae2v1hEyLlhHMnBxqllxI/Cf+DmW1eD0DgKoRiJgU2e3YPXY1qcldeEZ1zjiu7vwdCsDDduTgE0y0guIeTizgvY1GfZc3eK/qQtw7pUsyEfCzC/Bqi6oZ1mMWCNmtLsaSWrNHzo/IUD1PJCyGYc0tgx+8ryIbOM5znrVWTWVhBzGHmsx8yV+SRvLID9lFpc+ZZTTFwSuhvkOA6/rbz61uqJToYcWdScSFqdl/6cINsGCZYYoM="

language: c

os:
    - linux

dist: trusty
sudo: required

branches:
    only:
        - coverity-scan

before_install:
    - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - wget -c http://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - tar xf gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz
    - export PATH=$PATH:$PWD/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu/bin/
    - aarch64-linux-gnu-gcc --version
    # exporting the variable to be used by make utility
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export NUMCPUS=`nproc`
    - export XEN_TARGET_ARCH=arm64

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
        packages:
            - zlib1g-dev
            - libncurses5-dev
            - libssl-dev
            - python2.7-dev
            - xorg-dev
            - uuid-dev
            - libyajl-dev
            - libaio-dev
            - libglib2.0-dev
            - libpixman-1-dev
            - pkg-config
            - flex
            - bison
            - gettext
            - acpica-tools
            - bin86
            - bcc
            - libc6-dev-i386
            - libnl-3-dev
            - ocaml-nox
            - libfindlib-ocaml-dev
            - transfig
            - pandoc
            - gcc-arm-linux-gnueabihf
            - gcc-aarch64-linux-gnu
            - gcc-5
            - g++-5
            - clang-3.8
    coverity_scan:
        project:
            name: "xen-troops/xen"
            description: "Build submitted via Travis CI"
        notification_email: joculator@gmail.com
        build_command_prepend: "cov-configure --comptype gcc --compiler aarch64-linux-gnu-gcc --template"
        build_command: "make xen -j$NUMCPUS XEN_TARGET_ARCH=$XEN_TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE XSM_ENABLE=y CONFIG_HAS_SCIF=y CONFIG_DEBUG=y CONFIG_EARLY_PRINTK=salvator CONFIG_QEMU_XEN=n"
        branch_pattern: coverity-scan

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make xen -j$NUMCPUS XEN_TARGET_ARCH=$XEN_TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE XSM_ENABLE=y CONFIG_HAS_SCIF=y CONFIG_DEBUG=y CONFIG_EARLY_PRINTK=salvator CONFIG_QEMU_XEN=n; fi
