.gcc-tmpl:
  variables: &gcc
    CC: gcc
    CXX: g++

.clang-tmpl:
  variables: &clang
    LLVM_BIN_DIR: /opt/atfe/bin/
    CC: gcc
    CXX: g++
    HOSTCC: gcc
    HOSTCXX: g++
    clang: y
    llvm: y

.eclair-analysis:
  stage: analyze
  allow_failure: true
  variables:
    XEN_TARGET_ARCH: arm64
    KBUILD_DEFCONFIG: rel_arm64_defconfig
    EXTRA_XEN_CONFIG: |
      CONFIG_CMDLINE="xsm=flask flask=permissive"
      CONFIG_DEBUG=n
      CONFIG_DEBUG_INFO=n
    ECLAIR_OUTPUT_DIR: "ECLAIR_out"
    ANALYSIS_KIND: "normal"
    VARIANT: "ARM64"
    LOGFILE: "eclair-${VARIANT}-${RULESET}.log"
  before_script:
    # Kill eclair_report server (if running), because DB will be updated after analysis
    - pkill eclair_report || true
  script:
    - export PATH=${LLVM_BIN_DIR}:$PATH
    - ./automation/renesas-scripts/eclair 2>&1 | tee "${LOGFILE}"
  after_script:
    # Store latest analysis result
    - rm -fr /home/gitlab-runner/xen_latest || true
    - mkdir -p /home/gitlab-runner/xen_latest || true
    - cp -r ./ECLAIR_out /home/gitlab-runner/xen_latest
  artifacts:
    paths:
      - "${ECLAIR_OUTPUT_DIR}/*.log"
      - "${ECLAIR_OUTPUT_DIR}/*.txt"
      - "${ECLAIR_OUTPUT_DIR}/html/*"
      - "*.log"
      - "*.json"
      - "intermediates/"
    reports:
      codequality: code-quality-report.json
    when: always
  rules:
    - when: manual
  needs: []
  tags:
    - epdefrans

eclair-gcc-monitored:
  extends: .eclair-analysis
  variables:
    RULESET: "monitored"
    <<: *gcc

eclair-gcc-accepted:
  extends: .eclair-analysis
  variables:
    RULESET: "accepted"
    <<: *gcc

eclair-clang-monitored:
  extends: .eclair-analysis
  variables:
    RULESET: "monitored"
    <<: *clang

eclair-clang-accepted:
  extends: .eclair-analysis
  variables:
    RULESET: "accepted"
    <<: *clang

eclair-server-start:
  stage: analyze
  variables:
    TERM: xterm
  script:
    # This job will spin until eclair_report server is killed
    - |
      echo 'Run command on your local machine: \
      ssh -L 3786:localhost:3786 -N <user>@10.13.64.194 \
      and open report at http://127.0.0.1:3786'
    - /opt/bugseng/eclair/bin/eclair_report -verbose -db=/home/gitlab-runner/xen_latest/ECLAIR_out/PROJECT.ecd -browser -server || true
  rules:
    - when: manual
  needs: []
  tags:
    - epdefrans

eclair-server-stop:
  stage: analyze
  script:
    - ps -aux | grep eclair_report || true
    - pkill eclair_report || true
  rules:
    - when: manual
  needs: []
  tags:
    - epdefrans

.xen-analysis-py:
  stage: analyze
  image: xentroops/xen_rel
  allow_failure: true
  variables:
    XEN_TARGET_ARCH: arm64
    KBUILD_DEFCONFIG: rel_arm64_defconfig
    EXTRA_XEN_CONFIG: |
      CONFIG_CMDLINE="xsm=flask flask=permissive"
      CONFIG_DEBUG=n
      CONFIG_DEBUG_INFO=n
    LOGFILE: "cppcheck.log"
    <<: *clang
  before_script:
    - mkdir -p binaries
    - make -C xen defconfig 2>&1 | tee "${LOGFILE}"
    - echo "${EXTRA_XEN_CONFIG}" >> xen/.config 2>&1 | tee "${LOGFILE}"
    - make -j$(nproc) -C xen olddefconfig 2>&1 | tee "${LOGFILE}"
  artifacts:
    paths:
      - "xen/cppcheck-report"
      - "xen/cppcheck-htmlreport"
      - "*.log"
    when: always
  rules:
    - when: manual
  needs: []
  tags:
    - aws-arm64

cppcheck-clang:
  extends: .xen-analysis-py
  script:
    - xen/scripts/xen-analysis.py --run-cppcheck --cppcheck-html -- -j$(nproc) 2>&1 | tee "${LOGFILE}"

cppcheck-misra-clang:
  extends: .xen-analysis-py
  script:
    - xen/scripts/xen-analysis.py --run-cppcheck --cppcheck-misra --cppcheck-html -- -j$(nproc) 2>&1 | tee "${LOGFILE}"

gen_coverage_report:
  stage: analyze
  tags:
    - aws-arm64
  image: xentroops/xen_rel
  script:
    - LCOV_ARGS=$(find ./ -name "*.info" -printf "-a %p "); lcov --rc lcov_branch_coverage=1 $LCOV_ARGS -o coverage.info
    - genhtml --substitute 's|arch/arm/efi/common-stub.c|common/efi/common-stub.c|g' --branch-coverage -o coverage-report coverage.info
    - tar -czf coverage-report.tar.gz coverage-report
  artifacts:
    paths:
      - coverage.info
      - coverage_data
      - coverage-report.tar.gz
  needs:
    - qemu-lldb-tests
    - qemu-xtf-tests
  rules:
    - if: '$RUN_COVERAGE == "true"'
      when: always
