.arm64-build-tmpl:
  stage: build
  image: xentroops/xen_rel
  variables:
    HYPERVISOR_ONLY: y
    XEN_TARGET_ARCH: arm64
    KBUILD_DEFCONFIG: rel_arm64_defconfig
    BASE_XEN_CONFIG: |
      CONFIG_CMDLINE="xsm=flask flask=permissive"
      CONFIG_DEBUG_INFO=y
    UBSAN_CONFIG: ""
    COVERAGE_CONFIG: ""
  before_script:
  - |
    export EXTRA_XEN_CONFIG="${BASE_XEN_CONFIG}
    ${UBSAN_CONFIG}
    ${COVERAGE_CONFIG}
    ${EXTRA_XEN_CONFIG}"
  script:
    - mkdir -p binaries
    - ./automation/renesas-scripts/build 2>&1 | tee build.log
  artifacts:
    paths:
      - binaries/xen
      - binaries/xen-syms
      - xen-config
      - '*.log'
      - '*/*.log'
    when: always
  needs: []
  rules:
    - if: '$RUN_UBSAN == "true"'
      variables:
        UBSAN_CONFIG: |
          CONFIG_UBSAN=y
          CONFIG_UBSAN_FATAL=y
    - if: '$RUN_COVERAGE == "true"'
      variables:
        COVERAGE_CONFIG: |
          CONFIG_NO_OPTIMIZE=y
    - when: always
  tags:
    - aws-arm64

.gcc-tmpl:
  variables: &gcc
    CC: gcc
    CXX: g++

.clang-tmpl:
  variables: &clang
    CC: clang
    CXX: clang++
    HOSTCC: gcc
    HOSTCXX: g++
    clang: y
    llvm: y

.arm64-build:
  extends: .arm64-build-tmpl
  variables:
    debug: n

.arm64-build-debug:
  extends: .arm64-build-tmpl
  variables:
    debug: y

.gcc-arm64-build:
  extends: .arm64-build
  variables:
    <<: *gcc

.gcc-arm64-build-debug:
  extends: .arm64-build-debug
  variables:
    <<: *gcc

.atfe-arm64-build:
  extends: .arm64-build
  variables:
    <<: *clang

.atfe-arm64-build-debug:
  extends: .arm64-build-debug
  variables:
    <<: *clang

# Jobs below this line

# Build jobs needed for tests

# Arm builds

xen-atfe-arm64:
  extends: .atfe-arm64-build

xen-atfe-arm64-earlyprintk:
  extends: .atfe-arm64-build
  variables:
    EXTRA_XEN_CONFIG: |
      CONFIG_EARLY_UART_CHOICE_PL011=y
      CONFIG_EARLY_UART_BASE_ADDRESS=0x9000000
  rules:
    - if: '$RUN_UBSAN == "true"'
