.build-tmpl: &build
  stage: build
  image: registry.gitlab.com/xen-project/xen/${CONTAINER}
  script:
    - mkdir -p binaries
    - ./automation/renesas-scripts/build 2>&1 | tee build.log
  artifacts:
    paths:
      - binaries/
      - xen-config
      - xen-cppcheck.txt
      - '*.log'
      - '*/*.log'
    when: always
  needs: []
  rules:
  - when: always

.gcc-tmpl:
  variables: &gcc
    CC: gcc
    CXX: g++

.clang-tmpl:
  variables: &clang
    CC: clang
    CXX: clang++
    clang: y

.arm64-build-tmpl:
  <<: *build
  variables:
    XEN_TARGET_ARCH: arm64
  tags:
    - arm64

.arm64-build:
  extends: .arm64-build-tmpl
  variables:
    debug: n

.arm64-build-debug:
  extends: .arm64-build-tmpl
  variables:
    debug: y

.gcc-arm64-build:
  extends: .arm64-build
  variables:
    <<: *gcc

.gcc-arm64-build-debug:
  extends: .arm64-build-debug
  variables:
    <<: *gcc

## Test artifacts common

.test-jobs-artifact-common:
  stage: build
  needs: []

# Jobs below this line

# Build jobs needed for tests

# Arm builds

debian-bookworm-gcc-arm64:
  extends: .gcc-arm64-build
  variables:
    CONTAINER: debian:bookworm-arm64v8

debian-bookworm-gcc-debug-arm64:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: debian:bookworm-arm64v8

alpine-3.18-gcc-arm64:
  extends: .gcc-arm64-build
  variables:
    CONTAINER: alpine:3.18-arm64v8

alpine-3.18-gcc-debug-arm64:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: alpine:3.18-arm64v8
    EXTRA_XEN_CONFIG: |
      CONFIG_UBSAN=y
      CONFIG_UBSAN_FATAL=y

alpine-3.18-gcc-arm64-randconfig:
  extends: .gcc-arm64-build
  variables:
    CONTAINER: alpine:3.18-arm64v8
    RANDCONFIG: y

alpine-3.18-gcc-debug-arm64-staticmem:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: alpine:3.18-arm64v8
    EXTRA_XEN_CONFIG: |
      CONFIG_EXPERT=y
      CONFIG_UNSUPPORTED=y
      CONFIG_STATIC_MEMORY=y

alpine-3.18-gcc-debug-arm64-static-shared-mem:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: alpine:3.18-arm64v8
    EXTRA_XEN_CONFIG: |
      CONFIG_UNSUPPORTED=y
      CONFIG_STATIC_MEMORY=y
      CONFIG_STATIC_SHM=y

alpine-3.18-gcc-debug-arm64-boot-cpupools:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: alpine:3.18-arm64v8
    EXTRA_XEN_CONFIG: |
      CONFIG_BOOT_TIME_CPUPOOLS=y

alpine-3.18-gcc-debug-arm64-earlyprintk:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: alpine:3.18-arm64v8
    EXTRA_XEN_CONFIG: |
      CONFIG_EARLY_UART_CHOICE_PL011=y
      CONFIG_EARLY_UART_BASE_ADDRESS=0x9000000

rel-gcc-debug-arm64:
  extends: .gcc-arm64-build-debug
  variables:
    CONTAINER: debian:bookworm-arm64v8
    KBUILD_DEFCONFIG: rel_arm64_defconfig

