# The MC/DC tool lives in its own repo (github.com/xen-troops/clang-qemu-mcdc)
# and is cloned by the jobs that need it.

variables:
  MCDC_TOOL_URI: "https://github.com/xen-troops/clang-qemu-mcdc.git"
  MCDC_TOOL_BRANCH: "master"

# Template for building Xen.

.atfe-arm64-build:
  stage: build
  image: xentroops/xen_rel
  variables:
    CC: clang
    CXX: clang++
    HOSTCC: gcc
    HOSTCXX: g++
    clang: y
    llvm: y
    debug: n
    HYPERVISOR_ONLY: y
    XEN_TARGET_ARCH: arm64
    KBUILD_DEFCONFIG: rel_arm64_defconfig
    BASE_XEN_CONFIG: |
      CONFIG_CMDLINE="xsm=flask flask=permissive"
      CONFIG_DEBUG_INFO=y
    CUSTOM_XEN_CONFIG: ""
  before_script:
    - |
      EXTRA_XEN_CONFIG="${BASE_XEN_CONFIG}"$'\n'
      EXTRA_XEN_CONFIG+="${CUSTOM_XEN_CONFIG}"
      export EXTRA_XEN_CONFIG
  script:
    - ./automation/renesas-scripts/build 2>&1 | tee build.log
  artifacts:
    paths:
      - 'binaries/xen'
      - 'binaries/xen-syms'
      - 'binaries/plugin.conf'
      - 'binaries/xen-dwarf.pickle'
      - 'xen-config'
      - '*.log'
      - '*/*.log'
    when: always
  needs: []
  tags:
    - aws-arm64

# Template for QEMU test jobs.

.test-job-qemu-arm64:
  stage: test
  image: xentroops/xen_rel
  rules:
    - when: on_success
  variables:
    LOGFILE: qemu-test-arm64.log
  artifacts:
    paths:
      - '*.serial'
      - '*.log'
      - 'coverage_data'
      - 'coverage_mcdc'
      - 'binaries/*.bin'
      - 'binaries/*.dtb'
    when: always
  tags:
    - aws-arm64

# Zephyr test list for the normal run on QEMU and HW pipelines

.zephyr-test-common: &zephyr_test_common
  TEST:
    # [XenValTestJob~~1->XenValTestCode~domctl_pausedomain_set~1]
    - "hyp-domctl-pausedomain"
    # [XenValTestJob~~1->XenValTestCode~domctl_unpausedomain_set~1]
    - "hyp-domctl-unpausedomain"
    # [XenValTestJob~~1->XenValTestCode~domctl_resumedomain_set~1]
    - "hyp-domctl-resumedomain"
    # [XenValTestJob~~1->XenValTestCode~domctl_max_vcpus_set~1]
    - "hyp-domctl-max-vcpus"
    # [XenValTestJob~~1->XenValTestCode~domctl_setvcpucontext_set~1]
    - "hyp-domctl-setvcpucontext"
    # [XenValTestJob~~1->XenValTestCode~domctl_getvcpucontext_get~1]
    - "hyp-domctl-getvcpucontext"
    # [XenValTestJob~~1->XenValTestCode~arm64_domctl_createdomain~1]
    - "hyp-domctl-createdomain"
    # [XenValTestJob~~1->XenValTestCode~domctl_max_mem~1]
    - "hyp-domctl-max-mem"

# The tests to be run only on QEMU pipelines

.zephyr-test-qemu: &zephyr_test_qemu
  TEST:
    - "hyp-domctl-bind-pt-irq"
    # [XenValTestJob~~1->XenValTestCode~domctl_deassign_device_set~1]
    - "hyp-domctl-deassign-device"
    # [XenValTestJob~~1->XenValTestCode~domctl_assign_device_set~1]
    - "hyp-domctl-assign-device"
    # [XenValTestJob~~1->XenValTestCode~arm64_get_cpupool_info~1]
    - "hyp-sysctl-cpupool-getinfo"
    # [XenValTestJob~~1->XenValTestCode~arm64_add_domain_to_cpupool~1]
    - "hyp-domctl-createdomain-cpupool"
    - "hyp-xen-version"
    # [XenValTestJob~~1->XenValTestCode~arm64_sysctl_physinfo_host~1]
    - "hyp-sysctl-physinfo"
    # [XenValTestJob~~1->XenValTestCode~sysctl_get_vmlist_using_sysctl~1]
    - "hyp-sysctl-getdomaininfolist"
    # [XenValTestJob~~1->XenValTestCode~arm64_domctl_getdomaininfo_domain~1]
    - "hyp-domctl-getdomaininfo"
    # [XenValTestJob~~1->XenValTestCode~domctl_destroy_domain_using_domctl~1]
    - "hyp-domctl-destroydomain"
    # [XenValTestJob~~1->XenValTestCode~arm64_domctl_cacheflush~1]
    - "hyp-domctl-cacheflush"
    # [XenValTestJob~~1->XenValTestCode~arm64_domctl_get_paging_mempool_size~1]
    - "hyp-domctl-get-paging-mempool-size"
    # [XenValTestJob~~1->XenValTestCode~arm64_domctl_set_paging_mempool_size~1]
    - "hyp-domctl-set-paging-mempool-size"
    # [XenValTestJob~~1->XenValTestCode~arm64_boot_time_cpupool_cpus~1]
    - "hyp-sysctl-cpupool-info"
    # [XenValTestJob~~1->XenValTestCode~arm64_create_default_boot_time_cpupool0~1]
    - "hyp-sysctl-cpupool-default"
    # [XenValTestJob~~1->XenValTestCode~arm64_enforce_cpu0_in_boot_time_cpupool0~1]
    - "hyp-sysctl-cpupool-cpu0"
    # [XenValTestJob~~1->XenValTestCode~arm64_assign_sched_to_boot_time_cpupool~1]
    - "hyp-sysctl-cpupool-boot-sched"
    # [XenValTestJob~~1->XenValTestCode~arm64_use_credit2_sched_by_default~1]
    - "hyp-sysctl-sched-credit2-default"
    # [XenValTestJob~~1->XenValTestCode~arm64_use_rtds_sched_if_selected_via_xen_cmd_line~1]
    - "hyp-sysctl-sched-rtds-cmdline"
    # [XenValTestJob~~1->XenValTestCode~arm64_use_rtds_sched_if_set_in_boot_time_cpupool~1]
    - "hyp-sysctl-sched-rtds-boot-cpupool"
    # [XenValTestJob~~1->XenValTestCode~arm64_use_rtds_sched_if_set_via_hypercall~1]
    - "hyp-sysctl-sched-rtds-create-cpupool"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_vcpus_based_on_edf~1]
    - "hyp-sysctl-sched-rtds-edf"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_support_extratime~1]
    - "hyp-sysctl-sched-rtds-extratime"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_tickle_pcpus~1]
    - "hyp-sysctl-sched-rtds-tickle"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_assign_new_vcpu_to_pcpu~1]
    - "hyp-sysctl-sched-rtds-assign-vcpu"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_deassign_offline_vcpu_from_pcpu~1]
    - "hyp-sysctl-sched-rtds-deassign-vcpu"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_configure_params_per_vcpu~1]
    - "hyp-domctl-sched-rtds-params"
    # [XenValTestJob~~1->XenValTestCode~rtds_sched_configure_params_per_domain~1]
    - "hyp-domctl-sched-rtds-params-dom"
    # [XenVerTestJob~~1->XenVerTestCode~vpci_dom0~1]
    - "hyp-vpci-dom0"
    # [XenVerTestJob~~1->XenVerTestCode~vpci_dom0_msix~1]
    - "hyp-vpci-dom0-msix"
    # [XenVerTestJob~~1->XenVerTestCode~vpci_dom0_sriov~1]
    - "hyp-vpci-dom0-sriov"
    # [XenVerTestJob~~1->XenVerTestCode~vpci_domu~1]
    - "hyp-vpci-domu"
    # [XenVerTestJob~~1->XenVerTestCode~sysctl_cpu_hotplug~1]
    - "hyp-sysctl-cpu-hotplug"
    # [XenValTestJob~~1->XenValTestCode~arm64_virt_psci_system_suspend_explicit_resume~1]
    - "vpsci/system-suspend/explicit-resume"
    # [XenValTestJob~~1->XenValTestCode~arm64_virt_psci_system_suspend_inval_epoint~1]
    - "vpsci/system-suspend/invalid-entry"
    # [XenValTestJob~~1->XenValTestCode~arm64_virt_psci_system_suspend_32_bit_call_conv~1]
    - "vpsci/system-suspend/32-bit-arguments"
    # [XenValTestJob~~1->XenValTestCode~arm64_virt_psci_system_suspend_rej_secondaty_cpu_online~1]
    - "vpsci/system-suspend/secondary-online"

.zephyr-test-matrix:
  parallel:
    matrix:
      - *zephyr_test_common
      - *zephyr_test_qemu

.zephyr-test-matrix-hw:
  parallel:
    matrix:
      - *zephyr_test_common

# Define Zephyr test list for the LLDB approach.

.lldb-test-matrix:
  parallel:
    matrix:
      - TEST_SCRIPT:
        - "sched_core_scheduler_init.py"
        - "sched_core_scheduler_init_cpu_sched_up_fail.py"
        - "sched_core_scheduler_init_domain_create_fail.py"
        - "sched_core_scheduler_init_get_by_name_default_fail.py"
        - "sched_core_scheduler_init_global_init_fail.py"
        - "sched_core_scheduler_init_nr_cpu_ids_fail.py"
        - "sched_core_scheduler_init_sched_init_fail.py"
        - "sched_core_scheduler_init_sched_ratelimit_max.py"
        - "sched_core_scheduler_init_sched_ratelimit_min.py"
        - "sched_core_scheduler_init_test_func_fail.py"
        - "sched_core_scheduler_init_vcpu_create_fail.py"
