.test-jobs-common:
  stage: test
  image: xentroops/${CONTAINER}
  rules:
  - when: on_success

.arm64-test-needs: &arm64-test-needs
  - linux-6.6.86-image-export
  - alpine-3.18-rootfs-export

.arm64-xtf-test-needs: &arm64-xtf-test-needs
  - alpine-3.18-gcc-arm64
  - linux-6.6.86-image-export

.qemu-arm64:
  extends: .test-jobs-common
  variables:
    CONTAINER: xen_rel
    LOGFILE: qemu-smoke-arm64.log
  artifacts:
    paths:
      - '*.serial'
      - '*.log'
    when: always
  tags:
    - arm64

# Test jobs
qemu-smoke-dom0-arm64-gcc:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0-arm64.sh 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-arm64

qemu-smoke-dom0-arm64-gcc-debug:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0-arm64.sh 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64

qemu-smoke-dom0less-arm64-gcc:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-arm64

qemu-smoke-dom0less-arm64-gcc-debug:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64

qemu-smoke-dom0less-arm64-gcc-debug-gicv3:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh gicv3 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64

qemu-smoke-dom0less-arm64-gcc-debug-staticmem:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh static-mem 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64-staticmem

qemu-smoke-dom0less-arm64-gcc-debug-staticheap:
 extends: .qemu-arm64
 script:
   - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh static-heap 2>&1 | tee ${LOGFILE}
 needs:
   - *arm64-test-needs
   - alpine-3.18-gcc-debug-arm64

qemu-smoke-dom0less-arm64-gcc-debug-static-shared-mem:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh static-shared-mem 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64-static-shared-mem

qemu-smoke-dom0less-arm64-gcc-debug-boot-cpupools:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh boot-cpupools 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64-boot-cpupools

qemu-smoke-dom0less-arm64-gcc-debug-earlyprintk:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh earlyprintk 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64-earlyprintk

###XTF###

# XTF is run in dom0

qemu-xtf-dom0-arm64-gcc-hyp-xen-version:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-xen-version 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-xtf-dom0-arm64-gcc-debug-hyp-xen-version:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-xen-version 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_sysctl_physinfo_host~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-sysctl-physinfo:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-sysctl-physinfo 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_domctl_cacheflush~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-cacheflush:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-cacheflush 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~domctl_destroy_domain_using_domctl~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-destroydomain:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-destroydomain 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-pausedomain:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-pausedomain 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_domctl_set_paging_mempool_size~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-set-paging-mempool-size:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-set-paging-mempool-size 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-unpausedomain:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-unpausedomain 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~sysctl_get_vmlist_using_sysctl~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-sysctl-getdomaininfolist:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-sysctl-getdomaininfolist 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_domctl_getdomaininfo_domain~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-getdomaininfo:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-getdomaininfo 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_domctl_createdomain~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-createdomain:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-createdomain 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~arm64_domctl_get_paging_mempool_size~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-get-paging-mempool-size:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-get-paging-mempool-size 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~~1->XenValTestCode~domctl_max_mem~1]
qemu-xtf-dom0-arm64-gcc-debug-hyp-domctl-max-mem:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-max-mem 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

# [XenValTestJob~arm64_use_rtds_sched_if_selected_via_xen_cmd_line~1]
qemu-smoke-dom0less-arm64-rtds_sched_cmdline:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-smoke-dom0less-arm64.sh rtds_sched_cmdline 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-test-needs
    - alpine-3.18-gcc-debug-arm64

qemu-xtf-dom0-arm64-hyp-domctl-sched-rtds-edf:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-xtf.sh arm64 mmu64le hyp-domctl-sched-rtds-edf 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-gdb-sched-init-panic:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-gdb.sh sched-core-sched-init-fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs
  rules:
    - when: manual

qemu-gdb-sched-init-success:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-gdb.sh sched-core-scheduler_init.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs
  rules:
    - when: manual

# Tests for scheduler_init()
qemu-lldb-sched-init-success:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-cpu-sched-up-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_cpu_sched_up_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-domain-create-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_domain_create_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-get-by-name-default-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_get_by_name_default_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-global-init-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_global_init_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-nr-cpu-ids-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_nr_cpu_ids_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-sched-init-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_sched_init_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-sched-ratelimit-max:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_sched_ratelimit_max.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-sched-ratelimit-min:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_sched_ratelimit_min.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-test-func-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_test_func_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs

qemu-lldb-sched-init-vcpu-create-fail:
  extends: .qemu-arm64
  script:
    - ./automation/renesas-scripts/qemu-lldb.sh sched_core_scheduler_init_vcpu_create_fail.py 2>&1 | tee ${LOGFILE}
  needs:
    - *arm64-xtf-test-needs
